### ISSUE TITLE
Use a New Library/Package/Technology

### ISSUE THREAD

**Issue by cwarmbrunn** [cwarmbrunn/it-takes-a-city#7]
### Requirement

------
- Research a new library/package/technology to implement in this project.

**Comment by cwarmbrunn** [comment]
During our kickoff meeting, Matt shared the following as an option for an npm package:

- [Bootstrap Package](https://www.npmjs.com/package/bootstrap#documentation)
-  Kaijam also mentioned a five star NPM package 

We would need to confirm if using the bootstrap package would count for this requirement.

**Comment by cwarmbrunn** [comment]
@faceless128  Can we get the five star npm package link here -  that way we can install it!

**Comment by faceless128** [comment]
https://www.npmjs.com/package/accessible-five-stars

**Comment by cwarmbrunn** [comment]
Konner is using .ejs and a new authentication technology for the login portion - this has been fulfilled! 

We are also using Tailwind.
